trigger:
  - main

variables:
  - name: vmImage
    value: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Validate'
    jobs:
      - job: Validate
        displayName: 'Validate'
        pool:
          vmImage: $(vmImage)
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: ./node_modules
            displayName: Cache npm packages

          - script: |
              npm ci
            displayName: 'Install Dependencies'

          - script: |
              npm audit --omit=dev
            displayName: 'Run audit'

          - script: |
              npm run lint
            displayName: 'Run lint'

          - script: |
              npm run typecheck
            displayName: 'Run typecheck'


  - stage: Deploy
    displayName: 'Deploy Applications'
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: Deploy
        displayName: 'Deploy Applications'
        environment: 'local-llm-desktop-production'
        pool:
          vmImage: $(vmImage)
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: windows-build
                  displayName: 'Download Windows Build'
                - download: current
                  artifact: mac-build
                  displayName: 'Download Mac Build'

